# Generated by Django 5.2.11 on 2026-02-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waste',
            name='price_per_kg',
        ),
        migrations.AddField(
            model_name='waste',
            name='estimated_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
