# Generated by Django 5.2.11 on 2026-02-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_remove_waste_price_per_kg_waste_estimated_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='waste_images/'),
        ),
    ]
